name = "Oneirophobia SMP"
author = "Chaotic"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b4fc9ec4e223a677e1912da1b80c55859b7d041ac02ea8f5e6a6e2b24593a7a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
