name = "Oneirophobia SMP"
author = "Chaotic"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50a7983fb56850ba754eda12d3692a239d9d2f70a4697545ccf7fea0ee9a7464"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
